timeout: 1800s
steps:

  - id: 'Install: backend'
    name: node:14
    dir: './backend'
    entrypoint: yarn
    args: ['install']

  - id: 'Build: backend'
    name: node:18
    dir: './backend'
    entrypoint: yarn
    args: ['build']

  - id: 'Deploy: backend'
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: 'bash'
    dir: './backend'
    args:
      - gcloud
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --entry-point=api
      - --runtime=nodejs18
      - --region=${_FUNCTION_REGION}
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
      - --egress-settings=all
      - --vpc-connector=projects/$PROJECT_ID/locations/${_VPC_ACCESS_REGION}/connectors/${_VPC_ACCESS_CONNECTOR_NAME}
