timeout: 1800s
steps:

  - id: 'Deploy: backend'
    name: "gcr.io/cloud-builders/gcloud"
    dir: './backend'
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --entry-point=api
      - --runtime=nodejs18
      - --region=${_FUNCTION_REGION}
      - --source=.
      - --trigger-http
      - --allow-unauthenticated
      - --egress-settings=all
      - --vpc-connector=projects/$PROJECT_ID/locations/${_VPC_ACCESS_REGION}/connectors/${_VPC_ACCESS_CONNECTOR_NAME}
